---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: /octodns/config
    enforce_order: false
    default_ttl: 300
  cncf:
    class: octodns.provider.googlecloud.GoogleCloudProvider
    project: cncf-ci
    #credentials_file: '/octodns/creds/gcp.json'

zones:
  k8s.cncf.ci.:
    sources:
      - config
    targets:
      - cncf
